# Generated by Django 2.2.5 on 2022-05-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20220525_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amenitys',
            new_name='amenities',
        ),
    ]
